### ISSUE TITLE
error in installing

### ISSUE THREAD

**Issue by supadupa2** [morghim/contract-payment#4]
when running the command:
`bench install-app https://github.com/morghim/contract-payment.git`
I end up with the following error:
```
~/frappe-bench/apps$ bench --site ep1.local install-app https://github.com/morghim/contract-payment.git
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe-user/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/frappe-user/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe-user/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe-user/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe-user/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe-user/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe-user/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe-user/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe-user/frappe-bench/env/lib/python3.10/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe-user/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe-user/frappe-bench/apps/frappe/frappe/commands/site.py", line 410, in install_app
    frappe.init(site=site)
  File "/home/frappe-user/frappe-bench/apps/frappe/frappe/__init__.py", line 252, in init
    setup_module_map()
  File "/home/frappe-user/frappe-bench/apps/frappe/frappe/__init__.py", line 1551, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe-user/frappe-bench/apps/frappe/frappe/__init__.py", line 1391, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe-user/frappe-bench/apps/frappe/frappe/__init__.py", line 1340, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'contract-payment'

```

any idea how to fix this?

**Comment by franciscobuendiao** [comment]
Instead of "contract-payment" use "contract_payment"

bench get-app contract_payment https://github.com/morghim/contract-payment.git
bench --site (your site) install-app contract_payment

After installed I'm having issues with https://github.com/morghim/contract-payment/issues/5

**Comment by morghim** [comment]
> Instead of "contract-payment" use "contract_payment"
> 
> bench get-app contract_payment https://github.com/morghim/contract-payment.git bench --site (your site) install-app contract_payment
> 
> After installed I'm having issues with #5

If you are frappe 14 & erpnext 14
use this 
bench get-app https://github.com/morghim/contract-payment.git —branch version-14
