### ISSUE TITLE
ModuleNotFoundError: No module named 'erpnext.payroll'

### ISSUE THREAD

**Issue by franciscobuendiao** [morghim/contract-payment#5]
How to solve this?

![Error](https://github.com/morghim/contract-payment/assets/25084259/36250b11-172a-460e-bc2b-4f1544ed3dd5)
![Version](https://github.com/morghim/contract-payment/assets/25084259/26b4c71a-2371-4d27-8ee2-fd095fc71816)

**Comment by franciscobuendiao** [comment]
![numpy](https://github.com/morghim/contract-payment/assets/25084259/415e0bc8-7617-4458-96ff-3bae141dbb98)

**Comment by franciscobuendiao** [comment]
### App Versions
```
{
	"contract_payment": "0.0.1",
	"erpnext": "14.70.6",
	"frappe": "14.76.2",
	"hrms": "14.28.5",
	"mexico_einvoice": "0.0.1",
	"payments": "0.0.1"
}
```
### Route
```
Form/Contract/new-contract-smokxiwkll
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 97, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 16, in savedocs
    doc = frappe.get_doc(json.loads(doc))
  File "apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "apps/frappe/frappe/model/base_document.py", line 94, in get_controller
    site_controllers[doctype] = _get_controller()
  File "apps/frappe/frappe/model/base_document.py", line 72, in _get_controller
    module = frappe.get_module(module_path)
  File "apps/frappe/frappe/__init__.py", line 1343, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/contract_payment/contract_payment/contract_payment/override/contract.py", line 26, in <module>
    from numpy import pad
ModuleNotFoundError: No module named 'numpy'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Contract\",\"name\":\"new-contract-smokxiwkll\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"party_type\":\"Customer\",\"is_signed\":0,\"company\":\"OBERPRO\",\"status\":\"Unsigned\",\"fulfilment_status\":\"N/A\",\"dues_period_\":\"Monthly\",\"requires_fulfilment\":0,\"document_type\":\"\",\"contract_payment\":1,\"contract_type\":\"12 Meses\",\"party_name\":\"Banco Multiva\",\"start_date\":\"2024-01-01\",\"end_date\":\"2024-12-31\",\"amount\":1000000,\"make_first_dues_on\":\"2024-06-12\",\"contract_terms\":\"<div class=\\\"ql-editor read-mode\\\"><p>X</p></div>\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery3600165501488812177081": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 950,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "ModuleNotFoundError: No module named 'numpy'"
}
```

**Comment by franciscobuendiao** [comment]
```
pip3 install numpy
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.26.4)
```

**Comment by cutec-chris** [comment]
have you found an solution ?
